### ISSUE TITLE
Align with protocol spec to use operation request payload for operation hash calculation

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree-core#112]
Currently, only create operation hash is using the request payload for operation hash calculation, rest of the operation request types use the entire request buffer. Need to align with protocol spec.

**Comment by OR13** [comment]
In particular https://github.com/decentralized-identity/sidetree-core/blob/master/docs/protocol.md#did-document-resolution

https://github.com/decentralized-identity/sidetree-core/blob/814b67ba6ce5e0a46bc104c115891bf30f202343/tests/RequestHandler.spec.ts#L197

Per the terminology:
`Operation hash | The hash of the JSON-formatted request of a Sidetree operation.`

Should be base64Url(sha256(bufferFromBase64Url( base64UrlEncodedOp ... or 

base64Url(sha256(bufferFromBase64Url( base64UrlEncodedOpPayload ... 

Its very confusing to call the base64url encoded sha256 hash of the operation payload json "the operation hash", because its not actually the hash of the operation.

I suggest the operation hash remain named, "Operation hash", and be base64Url of sha256 of bufferFromBase64Url of the base64UrlEncodedOperation... and the spec be updated.

IMO the create is wrong not the update. 

Alternatively "Operation Hash" could be renamed to "Operation Payload Hash", but it seems like not a good direction to go. ..The point of the opHash is to compare with previousOperations, not previous operation payloads...

**Comment by thehenrytsai** [comment]
Adding @csuwildcat.

@OR13 You are absolutely spot on with your observation. Up until recently the _operation hash_ has always been the hash of the _entire_ operation request buffer, however, @csuwildcat made a feedback saying that it would be desirable for the operation requester to know the _operation hash_ (thus requester's DID) before the request is sent to a Sidetree node, __even__ if `proofOfWork` is not included, and hence the change in _operation hash_ definition.

We considered security implications of hashing operation payload directly as _operation hash_ and it seem fine, and it has the benefit of the first _operation hash_ (of a create operation) being exactly the newly created DID, thus reducing a level of indirection.

But I totally agree with you that then it should have been called "operation payload hash" for clarity, so if you agree that this is the right approach, I will create an issue to make sure the rename happens.

**Comment by OR13** [comment]
That makes sense, and I have leveraged the deterministic DID feature your
describe, it is still possible even if the operationHash != hash of
operation payload. It is very helpful to know that what a did will be,
based on it's initial content.

**Comment by thehenrytsai** [comment]
@OR13 Just to be absolutely clear, I take it that your point is to keep _operation hash_ concept away from _deterministic DID_ right?

ie:
first operation hash will **NOT** be the DID.

Sounds very resonable, I will discuss with @csuwildcat and @arvinda et all and update the create operation hash and spec accordingly.

**Comment by OR13** [comment]
Correct, I think it's reasonable for DID = hash of create payload, and
operation hash = hash on encoded operation.

**Comment by csuwildcat** [comment]
@OR13 one concern I have about moving to the operation hash being the composition of the entirety of operation props/values is that it may lock in the user or writer into having to sequentially assemble/generate each operation, serializing the process, including any future POW additions. The case I was considering was one where a user has an 'unpublished' pairwise DID that they want to cast to the chain for whatever reason - let's say its a scenario where they need the chain to act as the definitive oracle. If they had to quickly publish multiple ops at the same time, they (or the writer) would have to do all the processing one after another. I am not sure how much of an issue this is, but I am weary of creating a condition where a potential downside exists without much upside, know what I mean?

**Comment by OR13** [comment]
This got me thinking...

The operation hash is required for updates, so operations are always
sequential, if the pow changes, the operation hash changes and this applies
to both the unpublished case, and the migration case.

In the case of migration from one chain or contract to another, the
existing pow should still be valid, if this were not the case, the
batchFile would change, and so would the anchor file... so everything would
need to be recreated.

The main issue I see with pow, is that the operation hash would not be
knowable by clients who don't do their own pow. But it would be knowable
for clients who do. This seems correct to me, essentially it's saying if
you follow the protocol and do all the work you can trust the node to just
anchor you. If you don't do all the work, you can still trust the node to
anchor you, but you won't be able to know the operation hash because you
have not done the pow.

As a side note if operations were also content addressable, there would not
be question about what the hash of an operation is.

In order for the DID to be the same, you would need to sequentially
migrate, old PoW is still valid, so old anchors an batchFiles are still
valid.

Without including the signature in the op hash, it might be possible for a
did to be stolen in a migration because the original public key was
compromised and the attacker was able to craft update operations and anchor
them... I guess this depends on the ordering of migration operations...

I think logically, in order to update you need to know the previous
operation hash makes sense. I also think it makes sense that the operation
hash be a function of the signature and payload, since together they
represent the end user's desire. if the header is also included, the
operation hash is the hash of the operation, and updates are now coupled to
proof of work.

I don't think i fully understood the pairwise DID example, the user or node
would still need to do the proof of work for each operation, and they would
still need to include the previous operation hash, which in the new system
will require a proof of work for the previous operation, in the old one,
they would still need to sequentially generate the operations, and the
proof of work, but they would not be explicitly linked until published.

I think i need to understand the link between pow and migrations better.

**Comment by thehenrytsai** [comment]
Fixed in a598104f844b1f62929ae12bb6ee05b546cf5f28, closing.
