### ISSUE TITLE
Remove dependency on DID method name in operation payload and operation processor

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree-core#130]
Consider removing dependency on DID method name in operation payload and operation processor.

Such as the `did` property in update operation payload.

This issue would be of high-priority since it breaks backwards compatibility.

**Comment by OR13** [comment]
seems like a good idea, since all the operations are stored by didUniqueSuffix, `did:methodName` seems like a waste of space.

I'm considering the case where a user creates the same did document on 2 implementations of sidetree.

after which the previousOperationHash is the same,  then the user updates their bitcoin did... then an attacker attempts to replay their update operation on their other sidetree account...

Having the did method name in the update operation locks the update to the did method. 

What other mechanism ensures this? Is it not the case that removing the method name would allow updates that are valid in one method to be valid in another (assuming they are played in the same order).

Maybe this is a desirable feature? or maybe i'm missing something.

**Comment by thehenrytsai** [comment]
@OR13, you are spot on as usual:

_Is it not the case that removing the method name would allow updates that are valid in one method to be valid in another (assuming they are played in the same order)._

This would be a _feature_, but we can debate if such feature is desirable/undesirable. @csuwildcat and I have talked about the possibility for the operations to exists on Sidetree methods running on different chains, or even potential migration if the underlying chain is compromised.

**Comment by thehenrytsai** [comment]
Fixed in 930ffe0276d5f0d3cb941b0595d27636c91448e6.
