### ISSUE TITLE
transactionTimeHash redundant to transactionTime aka blockNumber

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree-core#191]
https://github.com/decentralized-identity/sidetree-core/blob/master/docs/implementation.md#response-body-schema-2

Recently came across this when rendering a UI component for sidetree ethereum transactions... 

```
{
      "transactionNumber": "1",
      "transactionTime": "5546321",
      "transactionTimeHash": "0xc5546a7b58e9470c1a5f9dc6e629637161e18a7d8ed71fb4b908f68cc73c2685",
      "anchorFileHash": "<protected>"
    }
```

https://ropsten.etherscan.io/block/0xc5546a7b58e9470c1a5f9dc6e629637161e18a7d8ed71fb4b908f68cc73c2685

Seems like `transactionTimeHash` is redundant to `transactionTime`, but the actual transaction where the anchor occurs is:

https://ropsten.etherscan.io/tx/0x203a1c37bb9b5d967e5ed298b59d38a714f7728ac3bda96bd0d2f68c4e24bc92

Did I implement this wrong? Seems like:

transactionTime should be '5546321' aka block number.
transactionTimeHash should be `0x203a1c37bb9b5d967e5ed298b59d38a714f7728ac3bda96bd0d2f68c4e24bc92`

which is transactionHash not blockHash... but when I read the implementation guide:

```
     "transactionTime": "The logical blockchain time this transaction is anchored. Used for protocol version selection.",
      "transactionTimeHash": "The hash associated with the transaction time.",
```

I'm not familiar enough with the bitcoin implementation to know if this issue exists on that side as well.

**Comment by thehenrytsai** [comment]
Hi @OR13,

`transactionTimeHash` is needed for detecting block reorgs. Imagine the chain forks and two blocks with the same block number now have different transactions. Without `transactionTimeHash` there is no way for sidetree-core to detect this which can lead to incorrect states.

As you are aware of, the protocol intentionally creates this abstraction and does not dictate the implementation as long as the `transactionTime` is monotonically increasing, and the _time hash_ is always deterministic based on the transaction time. But one obvious way to implement it is to use the block number and block number hash. Using transaction number and transaction hash as an alternative seems dangerous, because in the even of a reorg, the same transaction can appear in both forks and sidetree-core would not know the difference between the two if transaction hash is used as opposed to block hash.

`transactionTime` being `5546321` looks good.
`transactionTimeHash` being `0xc5546a7b58e9470c1a5f9dc6e629637161e18a7d8ed71fb4b908f68cc73c2685` would be the correct hash.

**Comment by OR13** [comment]
@thehenrytsai thanks, i'm going to close this!
