### ISSUE TITLE
Can we store any DID method in any sidetree?

### ISSUE THREAD

**Issue by ebaizel** [decentralized-identity/sidetree-core#39]
The way the spec is currently written it seems like each DID method will be persisted in a specific sidetree.

However, since all DIDs follow the same spec, shouldn't any sidetree be able to store any DID.  eg, a bitcoin DID like `did:btc:hashxyz` could be included in a batch sent to the Ethereum sidetree,  which would in turn know how to process that DID and its deltas, since it'd be the same way of parsing it for `did:eth:hashxyx`.

**Comment by csuwildcat** [comment]
While it's possible all Sidetree-based DID Methods could conceivably share the same underlying IPFS operators, there are many issues that (as far as I can tell) block rooting of DID ops across multiple chains. It's a little hard for me to put into a terse description, but here are some of the factors:

1. Blockchains are basically used by the protocol as a giant linear clock, which align DID methods in a deterministic order. If you mix N + 1 of these 'clock systems' together, doing eval on what ops happened when in comparison to each other could be a complex, relativistic exercise fraught with dragons.
2. Because different chains require different underlying chain-logic, and their Observer implementations will likely need to be modified for future changes or bug fixes, thus each implementation would need to have some awareness and enforcement based on the protocol rev changes of the others. This in turn could have reverberating side-effects against their own logic.

These are just two big issues, but there are definitely more, so we're focused on the single-chain DID Method case for now (unless new information presents itself).

**Comment by ebaizel** [comment]
I can see why you wouldn't want to share the same data across blockchains.

the way i understand it is, a DID is simply a JWT.  and we batch these and store the anchor hash on the blockchain for future verification.  is there any processing or verification of the DIDs before they're returned?  or are they just returned as json?

**Comment by csuwildcat** [comment]
"The way i understand it is, a DID is simply a JWT. and we batch these and
store the anchor hash on the blockchain for future verification."

This is just a small part of the equation. Unlike a simple hash anchor to
time stamp a document, a DID changes state over time, which means states
need to be deterministically resolvable to their current state. The way the
lineage of state change is able to be evaluated deterministically is via
the chronological order of the chain + a protocol that uses things like
state backpointers and other variables. If you scattered the updates to a
DID across chains, you would run into relativistic issues related to
resolving the changes in state, because there would be no single truth in
which the logical clocks of the chains relate to one another.

**Comment by ebaizel** [comment]
that makes sense.  so we'd need to validate each delta as we process it.  and then in the event the delta is invalid (or the signature doesn't match one of the ones in the DDO), would we fail the entire batch save?  i can open a separate issue for this if you think that'd be better.

**Comment by thehenrytsai** [comment]
> in the event the delta is invalid (or the signature doesn't match one of the ones in the DDO), would we fail the entire batch save? i can open a separate issue for this if you think that'd be better.

It depends. Currently the protocol WILL fail the entire batch/transaction if an operation is not _well-formed_, but will NOT fail the entire transaction if operation is well-formed but signature is invalid. Feel free to open dedicated issues for discussing this further so we don't hijack this issue.

For your reference though, the transaction validity rules are specified in the [protocol doc](https://github.com/decentralized-identity/sidetree-core/blob/master/docs/protocol.md) under section "Sidetree Transaction Processing".

Closing this issue now.
